#!/bin/bash
# The name of the job, can be anything, simply used when displaying the list of running jobs
#$ -N MC_32
# Giving the name of the output log file
#$ -o $JOB_NAME-$JOB_ID.log
# # Combining output/error messages into one file
#$ -j y
#$ -q cerqt2.q
# # One needs to tell the queue system to use the current directory as the working directory
# # Or else the script may fail as it will execute in your top level home directory /home/username
#$ -cwd
# # With -V you pass the env variables, it's necessary. And the unset module is needed to remove some errors
#$ -V
# # Uncomment the following line if you want to know in which host your job was executed
 echo "Running on " `hostname`
# # Now comes the commands to be executed
# # Copy exe and required input files to the local disk on the node
#
cp -r /home/cmm10/* $TMPDIR
#cp input.dat $TMPDIR
#cp sub.sh $TMPDIR
#
# # Change to the execution directory
cd $TMPDIR/
ls
./run.sh
# # And run the exe
#./sub.sh input.dat
#
#rm -r INPUT
#rm -r OUTPUT
rm -r PROGRAM
rm -r results_sub
rm run.sh
rm sub*
rm input.dat
rm MC*
rm r_main
# # Finally, we copy back all important output to the working directory
#tar -czvf "results.tar.gz" $TMPDIR/
tar -czvf "$JOB_NAME-$JOB_ID.tar.gz" $TMPDIR
rm -r production*
rm -r OUTPUT
rm -r INPUT
ls
scp -r * /home/cmm10/results_sub/
cd /home/cmm10/
#
#
